# Site settings
title: ZhiJie,Li Personal Web
description: A blog about Zhi Jie Li
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhi Jie Li
user_description: Computer Engineer interested in Robotic and Internet Of Things.
user_title: Computer Engineer
email: zhijieli@buffalo.edu
twitter_username: lorem_ipsum
github_username:  SendToSpace
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
